version: "2.0"
services:
  db:
    image: mariadb
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
  redis:
    image: redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
  ouk:
    build: .
    image: ouk-app
    command: bash -c "rm -rf tmp/pids/server.pid && rails s -b 0.0.0.0 -p 3000"
    env_file:
      - '.env.docker'
    volumes:
      - bundle:/bundle
      - cache:/cache
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
volumes:
  bundle:
    driver: local
  cache:
    driver: local
  redis-data:
    driver: local
  mysql-data:
    driver: local